### ISSUE TITLE
Add items to the shopping cart

### ISSUE THREAD

**Issue by melaasar** [cs130-w21/test#2]
## User Story
As a shopper, I would like add items to a shopping cart so that I can purchase them later.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [x] Every item in the database will have an Add to Shopping Cart button
- [ ] The option to add should be clickable button

## Tasks
- [x] Add a database
- [x] Add a service for the database with API
- [ ] Build front end for the service

**Comment by melaasar** [comment]
More work is needed
